pub struct ExtensionResult {
    pub format: String,
    pub mime: String,
}

pub fn detect_by_extension(ext: &str) -> ExtensionResult {
    let (format, mime) = match ext {
        "pdf" => ("pdf", "application/pdf"),
        "doc" => ("doc", "application/msword"),
        "docx" => ("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        "xls" => ("xls", "application/vnd.ms-excel"),
        "xlsx" => ("xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
        "ppt" => ("ppt", "application/vnd.ms-powerpoint"),
        "pptx" => ("pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
        "odt" => ("odt", "application/vnd.oasis.opendocument.text"),
        "ods" => ("ods", "application/vnd.oasis.opendocument.spreadsheet"),
        "odp" => ("odp", "application/vnd.oasis.opendocument.presentation"),
        "rtf" => ("rtf", "application/rtf"),
        "txt" | "text" => ("txt", "text/plain"),
        "csv" => ("csv", "text/csv"),
        "tsv" => ("tsv", "text/tab-separated-values"),
        "md" | "markdown" => ("md", "text/markdown"),
        "html" | "htm" => ("html", "text/html"),
        "xml" => ("xml", "application/xml"),
        "json" => ("json", "application/json"),
        "png" => ("png", "image/png"),
        "jpg" | "jpeg" => ("jpg", "image/jpeg"),
        "webp" => ("webp", "image/webp"),
        "gif" => ("gif", "image/gif"),
        "bmp" => ("bmp", "image/bmp"),
        "tiff" | "tif" => ("tiff", "image/tiff"),
        "svg" => ("svg", "image/svg+xml"),
        "py" => ("py", "text/x-python"),
        "js" | "mjs" => ("js", "text/javascript"),
        "ts" | "tsx" => ("ts", "text/typescript"),
        "java" => ("java", "text/x-java-source"),
        "cpp" | "cc" | "cxx" => ("cpp", "text/x-c++src"),
        "c" => ("c", "text/x-csrc"),
        "cs" => ("cs", "text/x-csharp"),
        "php" => ("php", "text/x-php"),
        "rb" => ("rb", "text/x-ruby"),
        "go" => ("go", "text/x-go"),
        "rs" => ("rs", "text/x-rust"),
        "css" => ("css", "text/css"),
        "sql" => ("sql", "text/x-sql"),
        "sh" | "bash" => ("sh", "text/x-shellscript"),
        "yaml" | "yml" => ("yaml", "text/yaml"),
        "mp3" => ("mp3", "audio/mpeg"),
        "wav" => ("wav", "audio/wav"),
        "mp4" => ("mp4", "video/mp4"),
        "mkv" => ("mkv", "video/x-matroska"),
        "avi" => ("avi", "video/x-msvideo"),
        "mov" => ("mov", "video/quicktime"),
        "webm" => ("webm", "video/webm"),
        "zip" => ("zip", "application/zip"),
        "7z" => ("7z", "application/x-7z-compressed"),
        "tar" => ("tar", "application/x-tar"),
        "gz" | "gzip" => ("gz", "application/gzip"),
        _ => ("unknown", "application/octet-stream"),
    };
    ExtensionResult {
        format: format.to_string(),
        mime: mime.to_string(),
    }
}
