// Generated by tauri-specta at Rust build time.
// This committed stub lets TS compile before the first build; the real file
// overwrites it with the authoritative shapes.

export interface AppInfo {
  name: string;
  version: string;
  offline: boolean;
  ocr_engine: string;
}

export interface ImportedPage {
  id: string;
  source_path: string;
  mime: string;
  width: number;
  height: number;
  byte_size: number;
  source_hash: string;
  preview_path: string;
  thumbnail_path: string;
}

export type CommandError =
  | { kind: "Validation"; message: string }
  | { kind: "Image"; message: string }
  | { kind: "Io"; message: string };

export interface Corner { x: number; y: number }

export interface DetectedBoundary {
  corners: [Corner, Corner, Corner, Corner];
  confidence: number;
  fallback: boolean;
}

export interface WarpedPage {
  preview_path: string;
  width: number;
  height: number;
  warp_hash: string;
}

export type Preset =
  | "Original" | "Color" | "Auto" | "Document"
  | "BlackWhite" | "Grayscale" | "HighContrast";

export interface EnhancementParams {
  preset: Preset;
  brightness: number;
  contrast: number;
  sharpness: number;
  shadow_remove: number;
}

export interface EnhancedPage {
  preview_path: string;
  width: number;
  height: number;
  recipe_hash: string;
}

export type PageMode =
  | "Auto" | "SingleBlock" | "MultiBlock" | "SingleLine" | "SparseText" | "Table";

export interface OcrOptions {
  languages: string;
  mode: PageMode;
}

export interface OcrWord {
  text: string;
  bbox: [number, number, number, number];
  confidence: number;
  line: number;
}

export interface OcrResult {
  text: string;
  words: OcrWord[];
  languages: string;
}

export type PageSize = "A4" | "Letter" | "Legal" | "Original";
export type MarginSize = "None" | "Small" | "Normal";
export type Quality = "High" | "Balanced" | "Small";

export interface PdfExportOptions {
  page_size: PageSize;
  margin: MarginSize;
  quality: Quality;
  searchable: boolean;
}

export interface PdfExportWord {
  text: string;
  bbox: [number, number, number, number];
}

export interface PdfExportPage {
  image_path: string;
  width: number;
  height: number;
  words: PdfExportWord[] | null;
}

export type ImageFormatKind = "Png" | "Jpeg" | "Webp" | "Tiff";
